<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Solutions>Annium.Backend</Solutions>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Annium.DbUp.PostgreSql/Annium.DbUp.PostgreSql.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Annium.Testing" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Scripts/Init/*.sql" />
    <EmbeddedResource Include="Scripts/Migrations/*.sql" />
  </ItemGroup>
</Project>
