<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Solutions>Annium.Integrations</Solutions>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Annium.Integrations.AI.SemanticKernel/Annium.Integrations.AI.SemanticKernel.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Annium.Testing" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
</Project>
