<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>Backuper.Storage.Local</PackageId>
        <PackageVersion>0.1.0</PackageVersion>
        <Description>Backuper.Storage.Local</Description>
        <TargetFramework>netcoreapp2.2</TargetFramework>
        <OutputType>Library</OutputType>
        <DebugType>portable</DebugType>
        <WarningsAsErrors>true</WarningsAsErrors>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../Backuper.Storage.Abstract/Backuper.Storage.Abstract.csproj" />
    </ItemGroup>
</Project>