<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Solutions>Annium.Finance</Solutions>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../../core/Data/src/Annium.Data.Operations.Testing/Annium.Data.Operations.Testing.csproj" />
    <ProjectReference Include="../Annium.Finance.Providers.Tests.Lib/Annium.Finance.Providers.Tests.Lib.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
</Project>
