<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Solutions>Annium.Finance</Solutions>
    <OutputType>Library</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../../base/tests/Annium.Finance.Providers.Tests.Shared/Annium.Finance.Providers.Tests.Shared.csproj" />
    <ProjectReference Include="../../src/Annium.Finance.Providers.Crypto.Binance.Spot/Annium.Finance.Providers.Crypto.Binance.Spot.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
</Project>
