<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Solutions>Annium.Integrations</Solutions>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../../core/Configuration/src/Annium.Configuration.Yaml/Annium.Configuration.Yaml.csproj" />
    <ProjectReference Include="../../../../core/Core/src/Annium.Core.Entrypoint/Annium.Core.Entrypoint.csproj" />
    <ProjectReference Include="../../src/Annium.Social.Telegram/Annium.Social.Telegram.csproj" />
  </ItemGroup>
</Project>
