<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Solutions>Annium.Tools</Solutions>
    <OutputType>Library</OutputType>
    <IsPackable>false</IsPackable>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../../../core/Extensions/src/Annium.Extensions.Arguments/Annium.Extensions.Arguments.csproj" />
    <ProjectReference Include="../../../../../core/Net/src/Annium.Net.Http/Annium.Net.Http.csproj" />
    <ProjectReference Include="../../Annium.XRest.Core/Annium.XRest.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Scriban" />
  </ItemGroup>
</Project>
