<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Solutions>Annium.Backend</Solutions>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <NoWarn>$(NoWarn);NETSDK1206</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Annium.MessageBus.Kafka/Annium.MessageBus.Kafka.csproj" />
    <ProjectReference Include="../Annium.MessageBus.Tests.Load.Shared/Annium.MessageBus.Tests.Load.Shared.csproj" />
    <ProjectReference Include="../Annium.MessageBus.Tests.Shared/Annium.MessageBus.Tests.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Annium.Serialization.Json" />
    <PackageReference Include="Annium.Testing" />
    <PackageReference Include="Confluent.Kafka" />
    <PackageReference Include="Testcontainers.Kafka" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
</Project>
