<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Solutions>Annium.Backend</Solutions>
    <OutputType>Library</OutputType>
    <IsPackable>false</IsPackable>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../../core/Annium/src/Annium.Testing/Annium.Testing.csproj" />
    <ProjectReference Include="../../../../core/Logging/src/Annium.Logging.InMemory/Annium.Logging.InMemory.csproj" />
    <ProjectReference Include="../../src/Annium.Storage.Abstractions/Annium.Storage.Abstractions.csproj" />
  </ItemGroup>
</Project>
