<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <Solutions>Annium.Frontend</Solutions>
    <OutputType>Library</OutputType>
    <IsPackable>true</IsPackable>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../../core/Data/src/Annium.Data.Models/Annium.Data.Models.csproj" />
    <ProjectReference Include="../../../../core/Net/src/Annium.Net.Base/Annium.Net.Base.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
    <PackageReference Include="Microsoft.AspNetCore.WebUtilities" />
  </ItemGroup>
</Project>
