<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Solutions>Annium.Backend</Solutions>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <NoWarn>$(NoWarn);NETSDK1206</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Annium.MessageBus.Nats/Annium.MessageBus.Nats.csproj" />
    <ProjectReference Include="../Annium.MessageBus.Tests.Load.Shared/Annium.MessageBus.Tests.Load.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../../../core/Core/src/Annium.Core.Runtime/Annium.Core.Runtime.csproj" />
    <ProjectReference Include="../../../../core/Logging/src/Annium.Logging.InMemory/Annium.Logging.InMemory.csproj" />
    <ProjectReference Include="../../../../core/Serialization/src/Annium.Serialization.Json/Annium.Serialization.Json.csproj" />
    <PackageReference Include="NATS.Net" />
    <PackageReference Include="Testcontainers.Nats" />
  </ItemGroup>
</Project>
