<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Solutions>Annium.Finance</Solutions>
    <OutputType>Library</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Annium.Finance.Providers.Shared/Annium.Finance.Providers.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Annium.Net.Servers.Web" />
    <PackageReference Include="Annium.Testing" />
  </ItemGroup>
</Project>
