<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Solutions>Annium.Finance</Solutions>
    <OutputType>Library</OutputType>
    <IsPackable>true</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../../base/src/Annium.Finance.Providers.Shared/Annium.Finance.Providers.Shared.csproj" />
  </ItemGroup>
</Project>
