<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Solutions>Annium.Backend</Solutions>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Annium.Redis/Annium.Redis.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Annium.Testing" />
    <PackageReference Include="Testcontainers.Redis" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
</Project>
