<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Solutions>Annium.Integrations</Solutions>
    <OutputType>Library</OutputType>
    <IsPackable>true</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../openai/src/AI.OpenAI/AI.OpenAI.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Annium.Core.DependencyInjection" />
    <PackageReference Include="Annium.Core.Runtime" />
    <PackageReference Include="Microsoft.SemanticKernel" />
    <PackageReference Include="ModelContextProtocol.Core" />
  </ItemGroup>
</Project>
