<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Solutions>Annium.Base</Solutions>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../../base/Annium/src/Annium.Testing/Annium.Testing.csproj" />
    <ProjectReference Include="../../../../base/Logging/src/Annium.Logging.Shared/Annium.Logging.Shared.csproj" />
    <ProjectReference Include="../../src/Annium.Graylog.Logging/Annium.Graylog.Logging.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
</Project>
